[package]
name = "common"
# TODO: add concrete description
description = "Package description."
version = { workspace = true }
edition = { workspace = true }
authors =  { workspace = true }
license-file = { workspace = true }
keywords = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw-ownable = { workspace = true }
cw2 = {workspace = true }
thiserror = { workspace = true }
badges = { workspace = true } 
badge-nft = { workspace = true }
sg721-base = { workspace = true }
sg721 = { workspace = true }
sg-std = { workspace = true }
sg-metadata = { workspace = true }
cw721 = { workspace = true }
cw721-base = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }